### ISSUE TITLE
Cylr on Windows Server 2003

### ISSUE THREAD

**Issue by tej7gandhi** [orlikoski/CyLR#109]
Hello All,

Are you aware how I can run Cylr on Windows Server 2003?

Thanks and Regards
Tej Gandhi

**Comment by chapinb** [comment]
Hi there! It depends on what version of CyLR you are running. Since CyLR uses dotNet core, it is restricted to only run on platforms supported by that framework. 

* For dotnet core 3.1: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md
* For dotnet core 2.1: https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md
