### ISSUE TITLE
Collecting default artifacts from mounted image.

### ISSUE THREAD

**Issue by iD4rksid3** [orlikoski/CyLR#80]
I know there is configuration file -c in which we can spicify drive letter, my question is if I have the image of a PC mounted as G: drive, how do I collect the default Cylr artifacts and for all users?

**Comment by orlikoski** [comment]
Currently that is not supported.

Currently there are two primary modes of collection and they are: Default & Targeted

**Default**
 This collects files for all users on the machine and uses %systemroot% for Windows machines to determine the OS drive for collection

**Targeted**
This mode uses either in-line arguments or the `-c` flag to specify a file of line delimited files and/or folders to collect from

**Comment by begapu** [comment]
Will this be supported?

**Comment by orlikoski** [comment]
That depends. I like the idea but it will take me a while to add this functionality to the program. It would go faster and I'd fully support someone from the community taking it on to add it and submit a PR to merge it here.

If anyone is interested then please let me know.

**Comment by Gizmo44z** [comment]
Late to the show, but...

I don't know that it'd be a great permanent solution to the CyLR source, but I did make a version with a drive letter variable.  It doesn't have any exception handling and uses "C:" as a default value rather than environment variables, but I have got it to work for this specific reason with some quick modifications.

https://github.com/Gizmo44z/CyLR/releases

Do note that this has been a personal build based on the code provided by @orlikoski and I have included modified coding of user paths (thanks to @davidrudduck) plus my own set of collection artifacts.  If you require different artifacts for your collection, I recommend reviewing the CollectionPaths.cs on my branch and modifying, as needed.
