### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by slacker-kb** [orlikoski/CyLR#95]
Making my first attempt to actually modified some code.  When I run "build_win.ps1" it runs fine.  Next I run package_win.ps1 and it throws an error "CyLR\deployments\win-x64\CyLR.exe : The system cannot find the file specified."  Isn't that what I am trying to build?  

First time with .Net.  Should be a blast.   Thanks in advance.

**Comment by orlikoski** [comment]
Those  build files are meant for Travis CI and that's why the pathing isn't working when you try to do it locally.

Building with .NET can be confusing and hopefully this will help.

Look inside of the `build_win.ps1` file to find the commands that prep and compile the code to understand what that is actually doing.

The next step in the build process is only required if a single .exe is desired. This is usually done on final versions but not while testing. Look inside the `package_win.ps1` to see what it's doing. It uses an external program to package the library and executable files into a single binary.

Hope that helps to unblock you.

**Comment by slacker-kb** [comment]
Got it to build but my additions may have caused some problems.  Going to build a clean version off the code unchanged to make sure it works, then try my changes again.  Thanks!

**Comment by lkuik** [comment]
hey @slacker-kb  were you able to figure this out?
@orlikoski  and I willing to help out in case you still encounter any further issues.

Thanks

**Comment by slacker-kb** [comment]
I was able to figure the build issue out.  But trying at add functionality, I quickly got out of my depth.

**Comment by lkuik** [comment]
Thanks for the update, I will proceed to close this out, and let us know if you have anymore questions or feel free to join skadicommunity.slack.com and ask anything there :)
